### ISSUE TITLE
bytestructure-set! with bytevector or other bytestructure

### ISSUE THREAD

**Issue by retroj** [TaylanUB/scheme-bytestructures#10]
I'm working with CHICKEN Scheme, and encountered the following behavior.  From the documentation, I think I understand that one can set the contents of a bytestructure to either a bytevector or another bytestructure, and the contents would be copied over.  I'm not sure whether this is just a bug due to something I need to fix in the chicken port, a bug in bytestructures in general, a misprint in the readme, or just something I am misunderstanding.  Please advise.

    #;1> (define a (bytestructure (bs:struct `((a ,uint16)))))
    #;1> (bytestructure-set! a 'a 5)
    #;1> (define b (bytestructure (bs:struct `((a ,uint16)))))
    #;1> (bytestructure-set! b 'a 8)
    #;1> (bytestructure-set! a b)
    
    Error: Invalid value for writing into struct.: #<<bytestructure>>
    
            Call history:
    
            <syntax>          (bytestructure-offset480 bytestructure476)
            <syntax>          (bytestructure-descriptor482 bytestructure476)
            <syntax>          (##core#lambda (bytevector464469470 offset465471472 descriptor466473474) (##core#let ((bytevector464...
            <syntax>          (##core#begin (##core#let ((bytevector464 bytevector464469470) (offset465 offset465471472) (descript...
            <syntax>          (##core#let ((bytevector464 bytevector464469470) (offset465 offset465471472) (descriptor466 descript...
            <syntax>          (##core#begin (bytestructure-primitive-set!468 bytevector464 offset465 descriptor466 b))
            <syntax>          (bytestructure-primitive-set!468 bytevector464 offset465 descriptor466 b)
            <eval>    (##sys#call-with-values (##core#lambda () (bytestructure-unwrap467 a)) (##core#lambda (bytevector464...
            <eval>    (bytestructure-bytevector478 bytestructure476)
            <eval>    (bytestructure-offset480 bytestructure476)
            <eval>    (bytestructure-descriptor482 bytestructure476)
            <eval>    (values488 bytevector477 offset479 descriptor481)
            <eval>    (bytestructure-primitive-set!468 bytevector464 offset465 descriptor466 b)
            body/base.scm:150: setter         
            body/struct.scm:159: u8vector?    
            body/struct.scm:188: error              <--
    #;1> (bytestructure-set! a (bytestructure-bytevector b))
    #;1> (bytestructure-ref a 'a)
    5

**Comment by TaylanUB** [comment]
"John J. Foerch" <notifications@github.com> writes:

> I'm working with CHICKEN Scheme, and encountered the following
> behavior. From the documentation, I think I understand that one can
> set the contents of a bytestructure to either a bytevector or another
> bytestructure, and the contents would be copied over. I'm not sure
> whether this is just a bug due to something I need to fix in the
> chicken port, a bug in bytestructures in general, a misprint in the
> readme, or just something I am misunderstanding. Please advise.
>
> #;1> (define a (bytestructure (bs:struct `((a ,uint16)))))
> #;1> (bytestructure-set! a 'a 5)
> #;1> (define b (bytestructure (bs:struct `((a ,uint16)))))
> #;1> (bytestructure-set! b 'a 8)
> #;1> (bytestructure-set! a b)

Thanks for the bug report.  What part of the README gave the impression
that one may set a bytestructure to another bytestructure?  Quoting
relevant parts of the documentation:

    (bytestructure-set! bytestructure index ... value) syntax

    Traverses through bytestructure using bytestructure-unwrap with the
    given indices to acquire a triple of a bytevector, offset, and
    descriptor. Then, applies the setter of that descriptor to the
    bytevector, offset, and value. Or if the setter is #f, then value
    must be a bytevector; as many bytes as the size of the descriptor
    are copied from it into the bytevector, starting from the offset.

So bytestructure-set! itself supports bytevector arguments for when
there is no setter procedure, but not bytestructure arguments.  However,
bs:struct has its own setter procedure anyway:

    Struct descriptors are normally meant for indexing through, but also
    allow direct assignment. The value provided for assignment may be a
    Scheme vector as long as there are fields in the struct descriptor,
    which will assign all fields sequentially; or a list of two-element
    lists, which will assign any number of fields by name.

This means that in the expression (bytestructure-set! a x) where 'a' is
as defined in your code snippet, valid values for 'x' are vectors and
lists, but not bytevectors or bytestructures.

(To be honest I'm not sure why I kept the feature of bytestructure-set!
that falls back to bytevector-copy! when there is no setter procedure;
it seems inconsistent with what the setters of bs:struct, bs:vector and
bs:union implement, none of which allow bytevectors as arguments.  I may
think of removing that feature if it's not already popular.)

Taylan

**Comment by retroj** [comment]
In the section on bs:vector, it says this:

    One may also provide a bytevector, in which case as many bytes as the size of the bytestructure will be copied into it.

    ;; The results of this depend on endianness.
    ;; Only the first 6 bytes from the bytevector will be copied.
    (bytestructure-set! vec #u8(0 1 2 3 4 5 6 7 8))

And in the section on bs:struct:

    One may also provide a bytevector, in which case as many bytes as the size of the bytestructure will be copied into it.

    ;; The field 'x' is set to 0; the value of the field 'y' will
    ;; depend on endianness.
    ;; Only the first 3 bytes from the bytevector will be copied.
    (bytestructure-set! str #u8(0 1 2 3 4 5))

There is a similar note under bs:union.

My confusion about being able to provide a bytestructure was based on a misreading of the documentation for bs:pointer.

**Comment by TaylanUB** [comment]
"John J. Foerch" <notifications@github.com> writes:

> In the section on bs:vector, it says this:
>
> One may also provide a bytevector, in which case as many bytes as the size of the bytestructure will be copied into it.
>
> ;; The results of this depend on endianness.
> ;; Only the first 6 bytes from the bytevector will be copied.
> (bytestructure-set! vec #u8(0 1 2 3 4 5 6 7 8))
>
> And in the section on bs:struct:
>
> One may also provide a bytevector, in which case as many bytes as the size of the bytestructure will be copied into it.
>
> ;; The field 'x' is set to 0; the value of the field 'y' will
> ;; depend on endianness.
> ;; Only the first 3 bytes from the bytevector will be copied.
> (bytestructure-set! str #u8(0 1 2 3 4 5))
>
> There is a similar note under bs:union.

Whoops, you're right.  Sorry about that.

> My confusion about being able to provide a bytestructure was based on
> a misreading of the documentation for bs:pointer.

OK, thanks for clearing it up. :-)
