### ISSUE TITLE
on guile, type values (e.g., double) may clash with some from (system foreign)

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#13]
guile.scm re-exports double, etc.  This means when I (use-module (system foreign)) I always get a warning.  I'd prefer be required to (use-module (system foreign))

**Comment by mwette** [comment]
This is actually more severe.  bytestructures has a double type that clashes with guile's double type.  I'm guessing there are others (like int32) that may clash as well.  How to cope. I need to use system foreign.

**Comment by TaylanUB** [comment]
Using a prefix on either of the imports is one solution.

```
scheme@(guile-user)> (use-modules ((system foreign) #:prefix ffi:))
scheme@(guile-user)> ffi:double
$2 = 2
```

Is that satisfactory, or would you say it has a significant annoyance factor? I'm undecided.

**Comment by mwette** [comment]
> On Mar 22, 2017, at 10:30 AM, TaylanUB <notifications@github.com> wrote:
> 
> Using a prefix on either of the imports is one solution.
> 
> scheme@(guile-user)> (use-modules ((system foreign) #:prefix ffi:))
> scheme@(guile-user)> ffi:double
> $2 = 2
> Is that satisfactory, or would you say it has a significant annoyance factor? I'm undecided
> 
> 

That works, but ffi:bs:struct is slightly annoying.   I will go with it for now.  Thanks for the recommendation.  Note that I will have to use both ffi:double and foreign:double in the code.   

Take care,
Matt

**Comment by TaylanUB** [comment]
I was thinking of using bytestructure stuff without a prefix, and `(system foreign)` stuff with a prefix like `ffi:`. (Maybe `ffi:` is wrong for `(system foreign)` but you get the idea.) That's usually what I do when I do some minor testing where I import both bytestructures and `(system foreign)`.

**Comment by mwette** [comment]
> On Mar 22, 2017, at 1:08 PM, TaylanUB <notifications@github.com> wrote:
> 
> I was thinking of using bytestructure stuff without a prefix, and (system foreign) stuff with a prefix like ffi:. (Maybe ffi: is wrong for (system foreign) but you get the idea.) That's usually what I do when I do some minor testing where I import both bytestructures and (system foreign).
> 
> 

Ah, got it.  Food for thought.  I will think about it.   Changing things around should be small impact on coding the patterns: the bulk of ffi code will be autogenerated.

Matt
