### ISSUE TITLE
How to represent a function pointer?

### ISSUE THREAD

**Issue by amirouche** [TaylanUB/scheme-bytestructures#14]
Sorry, I already asked the question on IRC, but I forgot the answer.

Thanks in advance!

**Comment by TaylanUB** [comment]
Bytestructures doesn't have a concept of a function pointer per se. (So far anyway.) There is a `pointer` type, but it's meant for pointers to other bytestructures.

One could save a pointer by using a numeric descriptor of the correct size (e.g. `uint64` on 64-bit systems), but unfortunately there's no numeric descriptor that automatically chooses the correct size depending on platform.

I suppose such a descriptor would be useful. I will add one under the name `address` to differentiate it from `pointer`.

On the meanwhile, you can automatically use the correct descriptor by doing:

```scheme
(use-modules (bytestructures guile))
(use-modules ((system foreign) #:prefix ffi:))
(define address (case (ffi:sizeof '*) ((8) uint64) ((4) uint32)))
```

**Comment by amirouche** [comment]
Thanks a lot!

**Comment by TaylanUB** [comment]
Instead of the `address` thing I mentioned, I added `intptr_t` and `uintptr_t` to the `numeric` submodule, which are suitable for this purpose. (Which one you use doesn't matter if you don't actually use the address as an integer.)
