### ISSUE TITLE
how to handle anonymous pointer

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#15]
Please add to README process for handling anonymous pointers.  For example,
``
typedef struct _foo foo_t;
``
``
typedef struct bar {
  foo_t *foo;
} bar_t;
``
where ``struct _foo`` is never defined.

**Comment by TaylanUB** [comment]
One may use `bs:pointer` with a bogus type like `uint8`, or one may use the numeric types `intptr_t` or `uintptr_t`.

I've documented both of these options under `bs:pointer` now. (And documented `[u]intptr_t` under the numeric types, where they were missing.)

P.S.: The commonly used term for the situation in your example is [opaque pointer](https://en.wikipedia.org/wiki/Opaque_pointer).
