### ISSUE TITLE
error: re-export local varible: cstring-pointer (in guile 2.0.13)

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#16]
I get the following occasionally with guile-2.0.13.  I don't know if it is on my end or not. Happens when I #use-module inside a module.  Any ideas what it could be?

``;;; compiling /Users/mwette/repo/github.com/TaylanUB/scheme-bytestructures/bytestructures/guile.scm
;;; WARNING: compilation of /Users/mwette/repo/github.com/TaylanUB/scheme-bytestructures/bytestructures/guile.scm failed:
;;; ERROR: re-exporting local variable: cstring-pointer
``

**Comment by mwette** [comment]
If I change the module name and filename to cstring-pointer-x (.scm) it works.  I wonder if module and procedure name dup is having issue w/ rnrs-guile interface.

**Comment by TaylanUB** [comment]
mwette <notifications@github.com> writes:

> I get the following occasionally with guile-2.0.13. I don't know if it
> is on my end or not. Happens when I #use-module inside a module. Any
> ideas what it could be?
>
> ;;; compiling /Users/mwette/repo/github.com/TaylanUB/scheme-bytestructures/bytestructures/guile.scm
> ;;; WARNING: compilation of /Users/mwette/repo/github.com/TaylanUB/scheme-bytestructures/bytestructures/guile.scm failed:
> ;;; ERROR: re-exporting local variable: cstring-pointer

Thanks for the report and the hint about the module name.  I pushed a
fix to this problem.

Taylan
