### ISSUE TITLE
"void" pseudo-type might be useful

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#18]
Possible enhancement: Back on subject of the void (opaque) pointer, it might be useful to have a "void" pseudo-type so that dereferencing ``(bs:pointer void)`` generates an exception rather than trying to generate an int if one were to use, say, ``(bs:pointer int)``.

**Comment by TaylanUB** [comment]
I now implemented this through a special feature of the `bs:void` descriptor constructor, where it allows the symbol `void` in place of the content descriptor to create a void pointer descriptor which throws an error when you try to dereference it.

```
scheme@(guile-user)> (define bs (bytestructure (bs:pointer 'void)))
scheme@(guile-user)> (bytestructure-ref bs '*)  ;try to follow pointer to read value
ERROR: In procedure scm-error:
ERROR: Tried to follow void pointer.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> ,q
scheme@(guile-user)> (bytestructure-set! bs '* 123)  ;try to follow pointer to write value
ERROR: In procedure scm-error:
ERROR: Tried to follow void pointer.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> ,q
scheme@(guile-user)> (bytestructure-set! bs #xdeadbeef)  ;set the pointer value itself
scheme@(guile-user)> (bytestructure-ref bs)  ;read the pointer value itself
$3 = 3735928559
```

I didn't test this beyond the rudimentary, so if you find problems with the approach or bugs in its implementation, please notify. :-)
