### ISSUE TITLE
guile/pointer.scm speedup

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#22]
For efficiency, consider replacing 
```
(define bytevector-address-ref
  (case pointer-size
    ((1) bytevector-u8-ref)
    ...
    ((8) bytevector-u64-native-ref)))

(define bytevector-address-set!
  (case pointer-size
    ((1) bytevector-u8-set!)
    ...
    ((8) bytevector-u64-native-set!)))
```
with
```
(define bytevector-address-ref
  (case pointer-size
    ((8) bytevector-u64-native-ref)
    ...
    ((1) bytevector-u8-ref)))

(define bytevector-address-set!
  (case pointer-size
    ((1) bytevector-u64-native-set!)
    ...
    ((2) bytevector-u8-set!)))
```

**Comment by TaylanUB** [comment]
Look at those forms more carefully. ;-)
They just bind the `bytevector-address-xyz` identifiers conditionally to one of the procedures that appear in the arms of the case expression, at the time the `define` forms are evaluated.

**Comment by mwette** [comment]
> On Sep 29, 2017, at 9:26 AM, TaylanUB <notifications@github.com> wrote:
> 
> Look at those forms more carefully. ;-)
> They just bind the bytevector-address-xyz identifiers conditionally to one of the procedures that appear in the arms of the case expression, at the time the define forms are evaluated.
> 
Got it.  They are not procedures.  My bad.  Sorry.

**Comment by TaylanUB** [comment]
No probs! Thanks for your feedback. :-)
