### ISSUE TITLE
Cannot use bytestructures if it is installed by autotools

### ISSUE THREAD

**Issue by lantw44** [TaylanUB/scheme-bytestructures#23]
I saw this error when loading it with `use-modules`:
```
ERROR: no code for module (bytestructures r6 bytevectors)
```

It seems that this problem can be avoided by adding bytestructures/r6/bytevectors.scm to `SOURCES`.

**Comment by TaylanUB** [comment]
Thanks for the report.  I just pushed a commit that adds said file to
SOURCES, as well as adding all the files needed for include directives
to EXTRA_DIST.

A trivial test on my side seemed to indicate that everything works,
although I'm almost surprised that it does: I hadn't thought about this
before but I use 'include-from-path' a lot in the code.  I'm not exactly
sure how this works with 'guild compile' when the path in question is
not set manually.  Maybe 'guile.am' does some magic that makes this
work.

Please report if you face any further problems. :-)

Taylan

**Comment by lantw44** [comment]
I made packages for Fedora and Arch from commit 7ed31b1 to satisfy the dependency of Guix. I saw no problem when using Guix, so I think it really works.
