### ISSUE TITLE
Can use scheme-bytestructure with guile after `make install`

### ISSUE THREAD

**Issue by mthl** [TaylanUB/scheme-bytestructures#24]
Trying to install scheme-bytestructure on Fedora 25 which is a transitive dependency of Guix master.  I encouter the current error:

```
mthl@localhost:~/.local/scheme-bytestructures$ guile2.2 
GNU Guile 2.2.1
Copyright (C) 1995-2017 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> ,use (bytestructures guile)
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/local/share/guile/site/2.2/bytestructures/guile.scm
;;; compiling /usr/local/share/guile/site/2.2/bytestructures/guile/base.scm
;;; compiling /usr/local/share/guile/site/2.2/bytestructures/guile/utils.scm
;;; WARNING: compilation of /usr/local/share/guile/site/2.2/bytestructures/guile/utils.scm failed:
;;; ERROR: Syntax error:
;;; bytestructures/guile/utils.scm:2:19: include-from-path: file not found in path in subform "bytestructures/body/utils.scm" of (include-from-path "bytestructures/body/utils.scm")
;;; WARNING: compilation of /usr/local/share/guile/site/2.2/bytestructures/guile/base.scm failed:
;;; ERROR: Syntax error:
;;; bytestructures/guile/utils.scm:2:19: include-from-path: file not found in path in subform "bytestructures/body/utils.scm" of (include-from-path "bytestructures/body/utils.scm")
;;; WARNING: compilation of /usr/local/share/guile/site/2.2/bytestructures/guile.scm failed:
;;; ERROR: Syntax error:
;;; bytestructures/guile/base.scm:8:19: include-from-path: file not found in path in subform "bytestructures/body/base.scm" of (include-from-path "bytestructures/body/base.scm")
;;; compiling /usr/local/share/guile/site/2.2/bytestructures/guile/vector.scm
;;; WARNING: compilation of /usr/local/share/guile/site/2.2/bytestructures/guile/vector.scm failed:
;;; ERROR: Syntax error:
;;; bytestructures/guile/vector.scm:7:19: include-from-path: file not found in path in subform "bytestructures/body/vector.scm" of (include-from-path "bytestructures/body/vector.scm")
While executing meta-command:
ERROR: Syntax error:
/usr/local/share/guile/site/2.2/bytestructures/guile/vector.scm:7:19: include-from-path: file not found in path in subform "bytestructures/body/vector.scm" of (include-from-path "bytestructures/body/vector.scm")
```

This issue appears only when `GUILE_LOAD_COMPILED_PATH` is not properly set to `/usr/local/lib/guile/2.2/site-ccache` where my scheme-bytestructure go files are installed. As a consequence auto compilation is triggered and `scheme-bytestructure/body` directory is not found in  `/usr/local/share/guile/2.2/site/`.  I would suggest installing the files from this directory too.

Thanks.

**Comment by TaylanUB** [comment]
Mathieu Lirzin <notifications@github.com> writes:

> Trying to install scheme-bytestructure on Fedora 25 which is a transitive dependency of Guix master. I encouter the current error:
>
> [... snip ...]
> ERROR: Syntax error:
> /usr/local/share/guile/site/2.2/bytestructures/guile/vector.scm:7:19: include-from-path: file not found in path in subform "bytestructures/body/vector.scm" of (include-from-path "bytestructures/body/vector.scm")
>
> This issue appears only when GUILE_LOAD_COMPILED_PATH is not properly set to /usr/local/lib/guile/2.2/site-ccache where my scheme-bytestructure go files are installed. As a consequence auto compilation is triggered and scheme-bytestructure/body directory is not found in /usr/local/share/guile/2.2/site/. I would
> suggest installing the files in this directory too.
>
> Thanks.

I think I've fixed the issue.  Please report if you still encounter
problems with the latest version.

Taylan

**Comment by mthl** [comment]
It works great.  Thanks.
