### ISSUE TITLE
Numeric types need extensions

### ISSUE THREAD

**Issue by johnwcowan** [TaylanUB/scheme-bytestructures#3]
There should be types "complex64" and "complex128", consisting of pairs of float32 and double64 containing the real and imaginary parts respectively.

While I'm at it, "float64" instead of "double64" would agree more with various SRFIs.

The C-specific types should be available on R7RS as well, with sensible defaults (assume 64-bit little-endian, and have the implementer change them if necessary).

**Comment by TaylanUB** [comment]
- Complex is on the TODO.
- `double64` has now been renamed to `float64`.
- Appendix B of R7RS defines `cond-expand` feature identifiers for the C memory model and byte order of the platform.  Using these, r7/numeric should be able to provide a full set of C-specific types.  On the TODO.

**Comment by TaylanUB** [comment]
In fact, just dug out this; useful for future reference:

> [...] You can use cond-expand to decide what int and so on mean.  The
> memory model features aren't widely supported: this will encourage
> their provision by implementers.
>
> Specifically, ilp32 means that ints, longs, and pointers are 32 bits;
> lp64 means that only longs and pointers are 64 bits; llp64 means that
> long is 32 bits, "long long" is 64 bits, and so are pointers.  The
> first model is used by 32-bit Windows and Unix, the second by 64-bit
> Unix, and the third by 64-bit Windows.
>
-- J. Cowan

**Comment by TaylanUB** [comment]
All done.
