### ISSUE TITLE
Fully procedural interface would be useful

### ISSUE THREAD

**Issue by johnwcowan** [TaylanUB/scheme-bytestructures#4]
Currently, you cannot ref or set! a field in a bytestructure with a procedure, which means it cannot be passed to any higher-order procedure.  This should be possible, even inefficiently.

**Comment by TaylanUB** [comment]
It's trivial to implement, but I'm not sure what name I'd give these procedures:

```
(define (ref bs . indices)
  (if (null? indices)
      (bytestructure-ref bs)
      (apply ref (bytestructure-ref bs (car indices)) (cdr indices))))

(define (set bs . rest)
  (if (null? (cdr rest))
      (bytestructure-set! bs (car rest))
      (apply set (bytestructure-ref bs (car rest)) (cdr rest))))
````

Ideas?

**Comment by johnwcowan** [comment]
I would make these procedures -ref and -set!, which I think is what people expect.  The question then is what to do with the existing -ref and -set!.  Alternatively these could be -ref/dynamic and -set!/dynamic, since the flexibility they provide is probably not needed that often.

**Comment by TaylanUB** [comment]
The problem with making the default ref/set! be procedures is that the rest-arguments list needs to be allocated, meaning that mere ref/set operations cause, well, allocation, which isn't nice.  (Even though there's the macro API for maximum performance, I think it's good to avoid allocation for such simple operations.  Also the macro API isn't available for all...)

The `/dynamic` variants sound good, will add.

**Comment by TaylanUB** [comment]
Done.
