### ISSUE TITLE
`intptr_t` is wrong when cross-compiling

### ISSUE THREAD

**Issue by civodul** [TaylanUB/scheme-bytestructures#40]
Hello @TaylanUB,

As noted in https://issues.guix.gnu.org/44000, `intptr_t` is incorrect when cross-compiling (say) from 64-bit to 32-bit: since `arch32-bit?` is determined at macro-expansion time (_via_ `cond-expand`), it is `#false` in that case even though it should be `#true`.

I posted [a patch that solves the issue](https://issues.guix.gnu.org/issue/44000/attachment/1/1), but it's somewhat Guile-specific, so I suppose we'd need a more generic solution.

WDYT?

Ludo'.

**Comment by TaylanUB** [comment]
Presumably fixed in 1.0.9, please reopen if not.
