### ISSUE TITLE
-helper is a bad name

### ISSUE THREAD

**Issue by johnwcowan** [TaylanUB/scheme-bytestructures#5]
Using -helper chooses identifiers based on purpose rather than function.  Better to give the triple of bytevector, descriptor, and offset a name such as "location", and then use "bytestructure-location" instead of "bytestructure-ref-helper".

**Comment by TaylanUB** [comment]
I'm having difficulties coming up with a good name.  Maybe `bytestructure-unwrap`?

**Comment by TaylanUB** [comment]
I just pushed a commit that changes all occurrences of "ref-helper" to either "unwrapper" or "unwrap" depending on context.  I like the name and am closing the ticket for now, but further suggestions still welcome.  (Especially since it's past 1 AM and I might be making bad decisions.)
