### ISSUE TITLE
version

### ISSUE THREAD

**Issue by retroj** [TaylanUB/scheme-bytestructures#8]
For purpose of a CHICKEN Scheme port, the project needs a version number, as version is a required piece of metadata for package installation.  The way that I would usually go about this is to create a file in the project root, that either contains the version in an easy-to-parse form (such as bare) or a version.scm containing (define version "1.0.0").  CHICKEN is partial to the x.y.z formatted version numbers with no alphabetic characters included.  I have been using the semantic version convention in projects recently (http://semver.org/).

**Comment by TaylanUB** [comment]
Would a file called version-for-chicken containing "0.1.0" in the root of the repo satisfy for now? Still not knowing about a single user of my library, I'd like to commit myself to a stable API (1.0.0) as late as possible.

**Comment by retroj** [comment]
If you would prefer that versioning be done only for chicken, then I can put the file in the `chicken/` directory and not pollute the root directory.  I thought that it might be useful for other schemes as well, and if it were, one canonical version file for all in the root (or in `bytestructures/` where it can be included for runtime) would be best.

I will follow your direction on the semantics of version components.

**Comment by TaylanUB** [comment]
In that case, it's best to keep the file Chicken-specific for now and
not include it in the bytestructures repo.

I guess I can add a version file when I make an official 1.0 release and
start actually versioning releases.

**Comment by retroj** [comment]
Okay, I will, thank you.
